apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: settings-management-service-monitor
  namespace: rules-engine
  labels:
    app: settings-management-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: settings-management-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
