apiVersion: v1
kind: ConfigMap
metadata:
  name: rules-engine-config
  namespace: rules-engine
  labels:
    app: rules-engine
data:
  # Database configuration
  DB_HOST: "postgresql-deployment.shared.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "rules_engine"
  DB_USER: "rules_user"
  DB_SSL_MODE: "disable"
  
  # Service ports
  MANAGEMENT_PORT: "8080"
  EVALUATION_PORT: "8081"
  CALCULATOR_PORT: "8082"
  METRICS_PORT: "9090"
  
  # NATS configuration
  NATS_URL: "nats://nats.shared.svc.cluster.local:4222"
  NATS_CLUSTER: "local-cluster"
  
  # Telemetry configuration
  TELEMETRY_SERVICE_NAME: "rules-engine"
  TELEMETRY_EXPORTER: "jaeger"
  JAEGER_ENDPOINT: "http://jaeger.default.svc.cluster.local:14268/api/traces"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
