apiVersion: v1
kind: Namespace
metadata:
  name: rules-engine-frontend
  labels:
    name: rules-engine-frontend
    app.kubernetes.io/name: rules-engine-frontend
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-resource-quota
  namespace: rules-engine-frontend
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "4"
    pods: "10"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limit-range
  namespace: rules-engine-frontend
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
