apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaigns-management-service
  namespace: rules-engine
  labels:
    app: campaigns-management-service
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaigns-management-service
  template:
    metadata:
      labels:
        app: campaigns-management-service
        version: v1.0.0
    spec:
      containers:
      - name: campaigns-management-service
        image: campaigns-management:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: "campaigns_db"
        - name: DB_SSLMODE
          value: "disable"
        - name: NATS_URL
          value: "nats://nats-service:4222"
        - name: RULES_SERVICE_URL
          value: "http://rules-management-service:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
